### ISSUE TITLE
Import Select/ShadowDOM

### ISSUE THREAD

**Issue by awwester** [agutoli/react-styled-select#16]
Is usage in the ShadowDOM supported yet? I'm not able to import it, although I see the functionality is there in the demo. I would have assumed it would be something similar to Select.Async:

```
import Select from 'react-styled-select'

<Select.ShadowDOM>
```

However I noticed it is not added into the index.js file, in which the Select/Async file is. In the demo it is importing directly from lib. Is that possible when installing from npm or does the ShadowDOM file need to be added into index.js to be used?

**Comment by agutoli** [comment]
Hi, @awwester. I like your suggestion, I will do that soon... tks

**Comment by agutoli** [comment]
@awwester try plz the new release `2.2.0-beta`

**Comment by awwester** [comment]
@agutoli works for me, thanks for the quick turnaround!

**Comment by agutoli** [comment]
@awwester Thanks you for the good suggestion...
