### ISSUE TITLE
change font size of selected value

### ISSUE THREAD

**Issue by awwester** [agutoli/react-styled-select#17]
Many of the elements are able to change the font-size, however it appears that select-value does not have it enabled. The property we're needing is `--styled-select-value__font-size`

Could that be added in?

By the way, we're using this package in shadow dom so interacting with css the normal way doesn't work, however modifying these CSS variables does work.

**Comment by agutoli** [comment]
Yeah! I just added it.

New release `react-styled-select@2.2.3-beta`

**Comment by awwester** [comment]
works, thanks for adding that in :+1:
