### ISSUE TITLE
don't display selected option

### ISSUE THREAD

**Issue by awwester** [agutoli/react-styled-select#18]
We have a situation where when we click on the select value, we don't want to show the value/display in the select element, but rather just leave the value as nothing and continue displaying the placeholder. 

I've been trying a lot of things around onValueClick, onChange, and clearable, but haven't found any way to do this. Is this something that is possible currently?

**Comment by agutoli** [comment]
Hi, @awwester. Sorry about delay...

I think you can use `valueRenderer`, you can render aways the same label with it.

**Comment by awwester** [comment]
No problem on the delay, thanks for getting back. hmm yeah that works when styling the value like the placeholder and making the text be the same. Not ideal since the select still has the value and we're just tricking it to look like the placeholder, but solves the issue. Thanks.
