### ISSUE TITLE
isMulti is not working

### ISSUE THREAD

**Issue by DougWoodCDS** [agutoli/react-styled-select#29]
Hi,
I cannot get isMulti  to work:
```
<Select
          options={options}
          onOpen={this.onOpen}
          onChange={this.onChange}
          isMulti
        />
```

I believe you support it but do not find any examples or documentation of this ?
Thanks for any help

**Comment by DougWoodCDS** [comment]
never mind I figured it out. thanks

**Comment by agutoli** [comment]
Actually it's `multi`. 

I gonna update the readme soon. Sorry about that.

<Select
          options={options}
          onOpen={this.onOpen}
          onChange={this.onChange}
          multi
        />
