### ISSUE TITLE
is there support for 'closeMenuOnSelect' property ?

### ISSUE THREAD

**Issue by DougWoodCDS** [agutoli/react-styled-select#30]
I was unable to find any documentation on this.

**Comment by DougWoodCDS** [comment]
well it would require adding external logic for it, which isn't ideal. would you have a recommended approach for doing this ?

**Comment by agutoli** [comment]
In this case I need to implement. Is not too complex, although.

**Comment by agutoli** [comment]
Try release `1.3.1` plz. I added support for this event.
