### ISSUE TITLE
Access to key press events

### ISSUE THREAD

**Issue by awwester** [agutoli/react-styled-select#32]
I'm needing to modify one of the key press events to stop propagation coming from the select element, but it looks like that's not possible at this time - please correct me if I'm wrong.

Would it be possible to allow access to these events via the `onKeyPress`, `onKeyDown`, `onKeyUp` events, or should this be accomplished in a different way to stop propagation/bubbling of the events?

**Comment by agutoli** [comment]
try new version plz. 

`react-styled-select@1.4.0`

**Comment by awwester** [comment]
Thanks for the quick turnaround! This is now working in 1.4.0
