### ISSUE TITLE
Upgrade to support styled-components v4

### ISSUE THREAD

**Issue by haywirez** [agutoli/react-styled-select#33]
Seems like it stopped working with the new styled components v4, will investigate more tomorrow...could be a simple fix?

**Comment by haywirez** [comment]
Might be as easy as changing `innerRef` to `ref`, but tests are failing on master already so cannot really dive into it more atm

**Comment by EstebanMarin** [comment]
I think is worth moving all dependencies to the latest babel `^7`, Storybook `^4`, TypeScript. We can future prof the lib, at least before moving more things on top. I can give it a go, and do a PR?

**Comment by EstebanMarin** [comment]
I am moving this to an indepedent issue.

**Comment by agutoli** [comment]
Hi, @EstebanMarin. How are you doing? sure! You can send me a PR. This project is our/community. 

Thanks!

**Comment by agutoli** [comment]
@haywirez @EstebanMarin 
Try release `react-styled-select@2.0.0` plz.
