### ISSUE TITLE
Missing onBlur prop

### ISSUE THREAD

**Issue by Moinax** [agutoli/react-styled-select#38]
I believe the `onBlur` prop is missing.
I'm using `Formik` to handle form state, and I should be able to trigger the validation on the `onBlur` event. So when a user open the select and close it without selecting anything, the validation display the error message.
I (kind of) found a workaround to get it working by using the `onOpen` prop, but it feels wrong as it immediately display the validation error and not after closing the select.

**Comment by agutoli** [comment]
new version `2.1.4`

**Comment by agutoli** [comment]
hi @Moinax , can you try now, please?

**Comment by Moinax** [comment]
It's working as expected, thank you very much for your prompt answer on this 👍
