### ISSUE TITLE
Multi and Searchable does not work simultaneously

### ISSUE THREAD

**Issue by daveanders** [agutoli/react-styled-select#40]
Hi!

In your demo page setting multi and searchable together works, but in the most current npm package whenever multi is selected, searchable functionality goes away.

Maybe you have an unpublished newer version?

**Comment by agutoli** [comment]
Thanks @ricardosaraiva ! I really appreciate your help!

new release `react-styled-select@3.0.0`

**Comment by agutoli** [comment]
Thanks to report that bug, @daveanders !
