### ISSUE TITLE
First element of the menu always focuses

### ISSUE THREAD

**Issue by Spy-Seth** [agutoli/react-styled-select#9]
The first element of the menu seems to always be in focus state: 

<img width="342" alt="screenshot 2017-08-24 17 33 12" src="https://user-images.githubusercontent.com/95120/29674389-52258fda-88f2-11e7-9d61-282cb90a4f23.png">

Here my mouse is on the last element of the input

_And yes I start using it ;)_

**Comment by agutoli** [comment]
Ohh.. tks to start use that! :)

Can you test it please? 

release `0.0.16-alpha`
Demo: http://agutoli.github.io/

**Comment by Spy-Seth** [comment]
It good 👍
